<?php

function groceries_menu() {
  $items = array();
  $items['groceries'] = array(
    'title' => "Groceries",
    'page callback' => 'display_groceries',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function display_groceries() {
  $grocery_list = set_groceries();
  $output = '';
  $total_cost = 0;
  foreach($grocery_list as $item) {
    $cost = $item['price'] * $item['quantity'];
    $total_cost += $cost;
    $output .= $item['item'] . '
    <ul>
      <li>Price: $' . $item['price'] . '</li>
      <li>Quantity: ' . $item['quantity'] . '</li>
      <li>Total Cost: $' . $cost . '</li>
    </ul><br>';
  }
  $output .= '<p>Overall Cost: $' . $total_cost .'</p>';
  return $output;
}


function set_groceries() {
  $my_groceries['eggs'] = array(
    'item' => 'Dozen Eggs',
    'price' => 1.99,
    'quantity' => 2,
  );
  $my_groceries['meat'] = array(
    'item' => 'Steak',
    'price' => 4.99,
    'quantity' => 1,
  );

  $my_groceries['beer'] = array(
    'item' => 'Tecate',
    'price' => 11.99,
    'quantity' => 3,
  );

  $my_groceries['Chicken'] = array(
    'item' => 'Foster Farms Chicken',
    'price' => 2.99,
    'quantity' => 11,
  );

  return $my_groceries;
}
